name: Shell Commands 

on: [push]

jobs: 
  run-shell-command:
    runs-on: macos-latest
    steps: 
      - name: echo a string
        run: echo "Hardhat project"
      - name: mutiline script 
        run: |
          node -v 
          npm -v 

      - name: python Command
        run : |
          import platform 
          print(platform.process())
        shell: python 
